name: Dependency Submission

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v6
